### ISSUE TITLE
[milestone] rust tooling is GA

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/filecoin-common-node-api#28]
- [ ] A user should be able to write tests that use RPC method calls that use generated code. 
  Success here is the `bindings` crate has _full_ bindings for the following APIs:
  - [ ] The Common Node API.
    - [ ] https://github.com/ChainSafe/forest/issues/4528
    - [ ] Tooling to select appropriate methods from OpenRPC documents from the below.
  - [ ] `v0`
  - [ ] `v1`
    - [ ] Forest's v1 document needs to be complete and tested.
      - [ ] This requires deeper changes to Forest's `forest-tool api compare` test suite to test e.g methods that have changed between v0 and v1. See https://github.com/ChainSafe/forest/pull/4516
  - [ ] Bindings are ergonomic, i.e using `::cid::Cid` instead of `struct Cid(String)`. This will required schema extensions.
    We should consider using these bindings in Forest.
- [ ] All methods are covered in `test-suite`.
  - [ ] Schema coverage.
    All structs are exercised in the test suite. This may require fixture support, test setup/teardown support, and node resetting support.
    - [ ] Schema coverage of the Common Node API.
    - [ ] Schema coverage of the v1 API.
    - [ ] Schema coverage of the v0 API.
  - [ ] Logic coverage.
    Tests like `GetHead`, `SetHead`, `GetHead` followed by an assertion.
    - [ ] Logic coverage of the Common Node API.
    - [ ] Logic coverage of the v1 API.
    - [ ] Logic coverage of the v0 API.
